# Generated by Django 3.0.6 on 2020-07-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week10_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contens',
            new_name='contents',
        ),
    ]
