# Generated by Django 3.0.6 on 2020-07-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week10_app', '0004_auto_20200725_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_author', to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
