# Generated by Django 3.0.6 on 2020-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week10_app', '0005_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='auth.User', max_length=100),
        ),
    ]
