# Generated by Django 3.0.6 on 2020-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_app', '0002_auto_20200629_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='photo',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
