# Generated by Django 3.0.6 on 2020-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=30)),
                ('cre_name', models.CharField(max_length=30)),
                ('prefer', models.IntegerField()),
                ('live', models.BooleanField(max_length=5)),
                ('sub_num', models.IntegerField()),
                ('link_1', models.TextField(max_length=50)),
                ('link_2', models.TextField(max_length=50)),
                ('link_3', models.TextField(max_length=50)),
            ],
        ),
    ]
