# Generated by Django 3.0.6 on 2020-05-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fav',
            field=models.TextField(blank=True),
        ),
    ]
